version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db 
    networks:
      - editor_network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    restart: always
    environment:
      MONGO_URI: mongodb://mongo:27017/authServiceDB
      JWT_SECRET: TU_SECRETO_SEGURO_AQUI
    expose:
      - "3002" 
    depends_on:
      - mongo
    networks:
      - editor_network

  drawings-service:
    build: ./drawings-service
    container_name: drawings-service
    restart: always
    environment:
      MONGO_URI: mongodb://mongo:27017/drawingsServiceDB
    expose:
      - "3001"
    depends_on:
      - mongo
    networks:
      - editor_network

  assets-service:
    build: ./assets-service
    container_name: assets-service
    restart: always
    expose:
      - "3003"
    volumes:
      - assets_uploads:/app/uploads 
    networks:
      - editor_network

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    restart: always
    depends_on:
      - auth-service
      - drawings-service
      - assets-service
    expose:
      - "3000" 
    networks:
      - editor_network

  nginx:
    image: nginx:latest
    container_name: vectra_editor_proxy
    restart: always
    ports:
      - "8080:80" 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf 
    depends_on:
      - gateway-service
    networks:
      - editor_network

volumes:
  mongo_data:
  assets_uploads:

networks:
  editor_network:
    driver: bridge